/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logicasinapsis.gui;
import logicasinapsis.estructuras.Grafo;
import logicasinapsis.estructuras.HashTable;
import logicasinapsis.lector.LectorCSV;
import logicasinapsis.algoritmos.AnalizadorConectividad;
import logicasinapsis.algoritmos.RutaDijkstra;
import logicasinapsis.modelo.Neurona;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;
import java.awt.Dimension;


import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;

// Importes de GraphStream
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;

/**
 *
 * @author luisg
 */
public class Interfazprincipal extends javax.swing.JFrame {
    
    
    private Grafo redNeuronal;
    private HashTable tablaNeurotransmisores;
    private AnalizadorConectividad analizador;
    private RutaDijkstra dijkstra;
    private LectorCSV lector;
    
    // --- ATRIBUTO VISUAL (GraphStream) ---
    private Graph graphVisual;
    private String[] ultimasZonasAisladas = new String[0];
    private String[] ultimaRutaDijkstra = new String[0]; // Guarda los IDs de los nodos de la ruta óptima
    private String nodoDestinoDijkstra = "";

    /**
     * Creates new form Interfazprincipal
     */
    public Interfazprincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Inicializar lógica propia (sin usar colecciones estándar)
        redNeuronal = new Grafo(100);
        tablaNeurotransmisores = new HashTable(50);
        analizador = new AnalizadorConectividad();
        dijkstra = new RutaDijkstra();
        lector = new LectorCSV();
        
        // Inicializar motor visual GraphStream
        System.setProperty("org.graphstream.ui", "swing");
        graphVisual = new SingleGraph("Cerebro");
        
        // Mensaje inicial en la interfaz
        jTextArea1.setEditable(false);
        jTextArea1.setText("Bienvenido a SynapseLogic.\n\n"
                + "1. Haga clic en 'Cargar Diccionario' para el Hash de Neurotransmisores.\n"
                + "2. Haga clic en 'Cargar Red Neuronal' para construir el Grafo.\n\n"
                + "El análisis lógico se realizará sin utilidades estándar de Java.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CargarDiccionario = new javax.swing.JButton();
        CargarRedNeuronal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CalculoRutaOptima = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Simularlesioncerebral = new javax.swing.JButton();
        SimularfatigaCognitiva = new javax.swing.JButton();
        ImplantarNuevaNeurona = new javax.swing.JButton();
        BFS = new javax.swing.JButton();
        DFS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SynapseLogic - Análisis de Conectividad y  Transmisión Neuronal.");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        CargarDiccionario.setText("Cargar Diccionario");
        CargarDiccionario.addActionListener(this::CargarDiccionarioActionPerformed);

        CargarRedNeuronal.setText("Cargar Red Neuronal");
        CargarRedNeuronal.addActionListener(this::CargarRedNeuronalActionPerformed);

        jLabel2.setText("Algoritmos y Diagnosticos:");

        CalculoRutaOptima.setText("Calculo Ruta Optima(Dijkstra)");
        CalculoRutaOptima.addActionListener(this::CalculoRutaOptimaActionPerformed);

        jLabel3.setText("Modificacion de la Red:");

        Simularlesioncerebral.setText("Simular lesion cerebral(Eliminar)");
        Simularlesioncerebral.addActionListener(this::SimularlesioncerebralActionPerformed);

        SimularfatigaCognitiva.setText("Simular Fatiga Cognitiva");
        SimularfatigaCognitiva.addActionListener(this::SimularfatigaCognitivaActionPerformed);

        ImplantarNuevaNeurona.setText("Implantar Nueva Neurona");
        ImplantarNuevaNeurona.addActionListener(this::ImplantarNuevaNeuronaActionPerformed);

        BFS.setText("BFS");
        BFS.addActionListener(this::BFSActionPerformed);

        DFS.setText("DFS");
        DFS.addActionListener(this::DFSActionPerformed);

        jLabel4.setText("Detectar Zona Aislada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CargarRedNeuronal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CargarDiccionario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CalculoRutaOptima, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BFS)
                                .addGap(18, 18, 18)
                                .addComponent(DFS))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ImplantarNuevaNeurona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SimularfatigaCognitiva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Simularlesioncerebral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarRedNeuronal)
                    .addComponent(CargarDiccionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalculoRutaOptima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BFS)
                            .addComponent(DFS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Simularlesioncerebral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SimularfatigaCognitiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImplantarNuevaNeurona)
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDiccionarioActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione el CSV de Neurotransmisores");
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            lector.cargarDiccionario(archivo.getAbsolutePath(), tablaNeurotransmisores);
            JOptionPane.showMessageDialog(this, "Diccionario HashTable cargado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CargarDiccionarioActionPerformed

    private void ImplantarNuevaNeuronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImplantarNuevaNeuronaActionPerformed
        // TODO add your handling code here:
       if (redNeuronal == null) {
        JOptionPane.showMessageDialog(this, "Debe cargar la red neuronal primero.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 1. Solicitar el ID de la nueva neurona a implantar
    String nuevoId = JOptionPane.showInputDialog(this, "Ingrese el ID para la nueva neurona (Ej: N99):");
    if (nuevoId == null || nuevoId.trim().isEmpty()) return;
    nuevoId = nuevoId.trim().toUpperCase();

    // Validar que no exista ya en la red en memoria
    if (redNeuronal.buscarNeurona(nuevoId) != null) {
        JOptionPane.showMessageDialog(this, "La neurona '" + nuevoId + "' ya existe en la red.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 2. Insertar la neurona físicamente en el grafo
    redNeuronal.agregarNeurona(new logicasinapsis.modelo.Neurona(nuevoId));
    
    // Contador para informar cuántas sinapsis se han creado
    int conexionesCreadas = 0;
    boolean seguirConectando = true;

    // 3. BUCLE INTERACTIVO: Permite conectar a 2 o más neuronas consecutivamente
    while (seguirConectando) {
        String mensajePrompt = (conexionesCreadas == 0) 
            ? "Ingrese el ID de la PRIMERA neurona destino existente para conectar (origen: " + nuevoId + "):"
            : "Lleva " + conexionesCreadas + " conexión(es).\nIngrese OTRO ID de neurona destino para conectar de inmediato\n(O pulse 'Cancelar' para finalizar):";

        String idDestino = JOptionPane.showInputDialog(this, mensajePrompt);
        
        // Si el usuario presiona Cancelar o deja vacío, se rompe el ciclo
        if (idDestino == null || idDestino.trim().isEmpty()) {
            seguirConectando = false;
            break;
        }
        
        idDestino = idDestino.trim().toUpperCase();
        
        // Validar si el destino ingresado existe en el grafo
        if (redNeuronal.buscarNeurona(idDestino) == null) {
            JOptionPane.showMessageDialog(this, "La neurona destino '" + idDestino + "' no existe.\nIntente con un ID válido.", "Neurona No Encontrada", JOptionPane.WARNING_MESSAGE);
            continue; // Regresa al inicio del bucle para pedir otra sin detener el proceso
        }

        try {
            // Solicitar distancia (d)
            String inputDist = JOptionPane.showInputDialog(this, "Conectando " + nuevoId + " -> " + idDestino + "\nIngrese la distancia de la sinapsis (double):", "2.5");
            if (inputDist == null) continue; // Si cancela este paso, salta a la siguiente iteración
            double distancia = Double.parseDouble(inputDist.trim());

            // Solicitar Neurotransmisor (ID)
            String inputNT = JOptionPane.showInputDialog(this, "Ingrese el ID del neurotransmisor (GLU, DA, GABA, ACH):", "GLU");
            if (inputNT == null) continue;
            String idNT = inputNT.trim().toUpperCase();

            // Solicitar coeficiente k
            String inputK = JOptionPane.showInputDialog(this, "Ingrese la eficiencia sináptica k (0.1 a 1.0):", "1.0");
            if (inputK == null) continue;
            double k = Double.parseDouble(inputK.trim());
            if (k < 0.1 || k > 1.0) k = 1.0; // Control regulatorio

            // CORRECCIÓN HISTÓRICA: Se conecta EN UN SOLO SENTIDO (Unidireccional)
            // Estímulo viaja estrictamente desde la Nueva Neurona hacia la Neurona Destino
            redNeuronal.conectar(nuevoId, idDestino, distancia, idNT, k);
            
            conexionesCreadas++;
            
            // Preguntar explícitamente si desea añadir otra conexión más
            int opcion = JOptionPane.showConfirmDialog(this, 
                    "¿Desea agregar otra conexión saliente adicional para la neurona '" + nuevoId + "'?", 
                    "Agregar múltiples enlaces", JOptionPane.YES_NO_OPTION);
            
            if (opcion != JOptionPane.YES_OPTION) {
                seguirConectando = false;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Formato numérico inválido. No se registró esta conexión.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 4. Mensaje de cierre de operación clínica
    if (conexionesCreadas > 0) {
        JOptionPane.showMessageDialog(this, "Implantación exitosa.\nSe integró la neurona '" + nuevoId + "' con " + conexionesCreadas + " sinapsis dirigidas.");
    } else {
        JOptionPane.showMessageDialog(this, "Neurona '" + nuevoId + "' implantada de forma aislada (Sin enlaces de salida).", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    // 5. Forzar la actualización inmediata en el mapa visual de GraphStream
    sincronizarGrafoVisual();
    if (conexionesCreadas > 0) {
        JOptionPane.showMessageDialog(this, "Implantación exitosa.\nSe integró la neurona '" + nuevoId + "' con " + conexionesCreadas + " sinapsis dirigidas.");
    } else {
        JOptionPane.showMessageDialog(this, "Neurona '" + nuevoId + "' implantada de forma aislada (Sin enlaces de salida).", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    // ==========================================
    // ¡AÑADE ESTO AQUÍ PARA CUMPLIR LA RÚBRICA!
    // ==========================================
    int respuestaSave = JOptionPane.showConfirmDialog(this, 
            "¿Desea guardar y exportar la red con la nueva neurona implantada en el archivo CSV?", 
            "Guardar Cambios", JOptionPane.YES_NO_OPTION);

    if (respuestaSave == JOptionPane.YES_OPTION) {
        guardarDatosEnArchivoCSV(); // Llama a tu función de guardado
    }
    // ==========================================

    // 5. Forzar la actualización inmediata en el mapa visual de GraphStream
    sincronizarGrafoVisual();
    }//GEN-LAST:event_ImplantarNuevaNeuronaActionPerformed
    private void guardarDatosEnArchivoCSV() {
        if (redNeuronal == null || redNeuronal.getCantidadNodos() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos cargados para guardar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JFileChooser selectorArchivo = new JFileChooser();
        selectorArchivo.setDialogTitle("Guardar Estado Clínico de la Red Neuronal (.csv)");
        
        // Filtro para forzar extensiones .csv
        selectorArchivo.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV (*.csv)", "csv"));
        int seleccion = selectorArchivo.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = selectorArchivo.getSelectedFile();
            String ruta = archivoSeleccionado.getAbsolutePath();

            // Si el usuario no escribió la extensión, se la anexamos automáticamente
            if (!ruta.toLowerCase().endsWith(".csv")) {
                ruta += ".csv";
            }

            // Ejecutamos la persistencia física
            lector.guardarRedCSV(ruta, redNeuronal);

            JOptionPane.showMessageDialog(this, 
                    "¡Datos sincronizados y guardados correctamente!\nArchivo: " + archivoSeleccionado.getName(), 
                    "Persistencia Exitosa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void SimularfatigaCognitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularfatigaCognitivaActionPerformed
        // TODO add your handling code here:
       if (redNeuronal == null || redNeuronal.getCantidadNodos() == 0) {
            JOptionPane.showMessageDialog(this, "Debe cargar la red neuronal primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. Ejecutar alteración matemática de fatiga clínica
        analizador.simularFatigaCognitiva(redNeuronal);

        // 2. Informar al usuario en pantalla
        JOptionPane.showMessageDialog(this, 
                "¡Simulación de Fatiga Cognitiva Aplicada!\n\n" +
                "El factor de eficiencia 'k' de todas las sinapsis se multiplicó por 1.2.\n" +
                "Esto altera el cálculo de pesos (W = d / (v * k)).\n\n" +
                "Ya puede volver a calcular Dijkstra o BFS para verificar si se crearon\n" +
                "nuevas zonas aisladas debido al cansancio del paciente.", 
                "Simulación Clínica Exitosa", JOptionPane.WARNING_MESSAGE);

        // 3. Ofrecer de inmediato la opción de resguardar los cambios realizados
        int respuesta = JOptionPane.showConfirmDialog(this, 
                "¿Desea exportar y guardar estos datos alterados en un archivo CSV ahora mismo?", 
                "Guardar Persistencia", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            guardarDatosEnArchivoCSV(); // Llamamos a la función de guardado
        }

        // 4. Refrescar el mapa visual para reflejar las nuevas variables k en las etiquetas
        sincronizarGrafoVisual();
    }//GEN-LAST:event_SimularfatigaCognitivaActionPerformed

    private void CargarRedNeuronalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarRedNeuronalActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Seleccione el archivo CSV de Neuronas/Sinapsis.");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione el CSV Estructural");
        
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String rutaEstructura = fileChooser.getSelectedFile().getAbsolutePath();
            
            try {
                // ¡AQUÍ ESTABA EL ERROR! Faltaba esta línea para leer el archivo realmente
                lector.cargarRed(rutaEstructura, redNeuronal);
                
                JOptionPane.showMessageDialog(this, "Red Neuronal cargada en memoria. Generando mapa visual...", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                sincronizarGrafoVisual();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error de lectura: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_CargarRedNeuronalActionPerformed

    private void CalculoRutaOptimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculoRutaOptimaActionPerformed
        // TODO add your handling code here:
        if (redNeuronal == null || redNeuronal.getCantidadNodos() == 0) {
            JOptionPane.showMessageDialog(this, "Debe cargar la red neuronal primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String origen = JOptionPane.showInputDialog(this, "Ingrese la neurona origen del estímulo:");
        if (origen == null || origen.trim().isEmpty()) return;

        // 1. Ejecutar Dijkstra y capturar el String del reporte limpio
        String reporteDijkstra = dijkstra.analizarRed(redNeuronal, tablaNeurotransmisores, origen);
        
        // 2. Crear un JTextArea dinámico en memoria para albergar el reporte
        javax.swing.JTextArea areaTextoPopup = new javax.swing.JTextArea(20, 45);
        areaTextoPopup.setText(reporteDijkstra);
        areaTextoPopup.setEditable(false); // El usuario no debe poder alterarlo
        areaTextoPopup.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12)); // Fuente tipo consola alineada
        
        // 3. Envolver el JTextArea en un JScrollPane flotante
        javax.swing.JScrollPane scrollPopup = new javax.swing.JScrollPane(areaTextoPopup);
        
        // 4. Lanzar el JOptionPane mostrando el scroll interactivo
        JOptionPane.showMessageDialog(this, scrollPopup, "Análisis Clínico de Rutas Óptimas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CalculoRutaOptimaActionPerformed

    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        // TODO add your handling code here:
       if (redNeuronal == null || redNeuronal.getCantidadNodos() == 0) {
            JOptionPane.showMessageDialog(this, "Primero cargue la red neuronal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String idFuente = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona origen para el estímulo:");
        if (idFuente == null || idFuente.trim().isEmpty()) return;

        String[] zonasAisladas = analizador.detectarZonasAisladas(redNeuronal, idFuente);
        
        StringBuilder sb = new StringBuilder();
        sb.append("--- ANÁLISIS DE CONECTIVIDAD (BFS) ---\n");
        sb.append("Neurona Origen del estímulo: ").append(idFuente).append("\n");
        sb.append("Zonas Aisladas detectadas (Inalcanzables): ").append(zonasAisladas.length).append("\n");
        for (String id : zonasAisladas) {
            sb.append(" -> Neurona ").append(id).append(" [AISLADA]\n");
            
            // Pintar de ROJO las zonas muertas en GraphStream para ganar puntos de diseño visual
            if (graphVisual.getNode(id) != null) {
                graphVisual.getNode(id).setAttribute("ui.style", "fill-color: red;");
            }
        }
        
        boolean esConexa = analizador.esFuertementeConexa(redNeuronal);
        sb.append("\n¿La red es fuertemente conexa actualmente?: ").append(esConexa ? "SÍ" : "NO (Red fragmentada)");
        
        jTextArea2.setText(sb.toString());
    }//GEN-LAST:event_BFSActionPerformed

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        // TODO add your handling code here:
        if (redNeuronal.getCantidadNodos() == 0) return;
        
        String fuente = JOptionPane.showInputDialog(this, "ID de la neurona fuente (Búsqueda DFS):");
        if (fuente != null && !fuente.trim().isEmpty()) {
            String[] aisladas = analizador.detectarZonasAisladas(redNeuronal, fuente);
            if (aisladas == null || aisladas.length == 0) {
                JOptionPane.showMessageDialog(this, "No hay zonas aisladas partiendo desde " + fuente + ".");
            } else {
                StringBuilder sb = new StringBuilder("Neuronas aisladas (Inalcanzables):\n");
                for (String aislada : aisladas) {
                    if (aislada != null) {
                        sb.append("- ").append(aislada).append("\n");
                        if (graphVisual.getNode(aislada) != null) {
                            graphVisual.getNode(aislada).setAttribute("ui.style", "fill-color: red;");
                        }
                    }
                }
                JOptionPane.showMessageDialog(this, sb.toString(), "Zonas Muertas", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_DFSActionPerformed
    private void sincronizarGrafoVisual() {
        try {
            // 1. Limpiar el grafo visual previo para redibujarlo de cero
            graphVisual.clear();
            
            // 2. HOJA DE ESTILOS ADAPTADA (Perfecta para GS 2.0 en Swing)
            graphVisual.setAttribute("ui.stylesheet", 
                "node { " +
                "   fill-color: #CCCCCC; " + 
                "   size: 24px; " + 
                "   text-size: 13px; " +          
                "   text-color: black; " + 
                "   text-alignment: center; " + 
                "} " +
                "edge { " +
                "   text-size: 10px; " +           
                "   text-color: #333333; " + 
                "   text-background-mode: plain; " + 
                "   text-background-color: white; " + 
                "   arrow-size: 8px, 5px; " +     
                "   text-offset: 0px, 3px; " + 
                "}");
            
            // 3. Añadir Nodos (Neuronas) desde el Grafo interno en memoria
            for (int i = 0; i < redNeuronal.getCantidadNodos(); i++) {
                logicasinapsis.modelo.Neurona n = redNeuronal.getNeuronaEnPosicion(i);
                if (n != null) {
                    org.graphstream.graph.Node nodoVisual = graphVisual.addNode(n.getId());
                    nodoVisual.setAttribute("ui.label", n.getId());
                    
                    // COMPROBACIÓN PERSISTENTE DEL BFS: Si la neurona está aislada, se fuerza a color ROJO
                    if (esZonaAislada(n.getId())) {
                        nodoVisual.setAttribute("ui.style", "fill-color: red; text-color: white;");
                    }
                }
            }
            
            // 4. Añadir Aristas (Sinapsis) con etiquetas y colores dinámicos
            for (int i = 0; i < redNeuronal.getCantidadNodos(); i++) {
                logicasinapsis.modelo.Neurona origen = redNeuronal.getNeuronaEnPosicion(i);
                if (origen == null) continue;
                
                logicasinapsis.estructuras.Grafo.ListaSinapsis.NodoSinapsis actual = 
                        redNeuronal.getPrimerNodoSinapsis(i);
                
                while (actual != null) {
                    String idDestino = actual.sinapsis.getDestino().getId();
                    String idArista = origen.getId() + "-" + idDestino;
                    
                    if (graphVisual.getEdge(idArista) == null) {
                        org.graphstream.graph.Edge aristaVisual = graphVisual.addEdge(idArista, origen.getId(), idDestino, true);
                        
                        double dist = actual.sinapsis.getDistancia(); 
                        String nt = actual.sinapsis.getIdNeurotransmisor(); 
                        double k = actual.sinapsis.getK(); 
                        
                        String etiqueta = String.format("d:%.1f (%s) k:%.1f", dist, nt, k);
                        aristaVisual.setAttribute("ui.label", etiqueta);
                        
                        // --- REQUERIMIENTO VISUAL DE DIJKSTRA: COLOR AZUL PARA RUTA ÓPTIMA ---
                        if (esAristaDeRutaOptima(origen.getId(), idDestino)) {
                            // Se pinta de un color Azul Eléctrico / Cian brillante y se hace más gruesa
                            aristaVisual.setAttribute("ui.style", "fill-color: #00CCFF; size: 4px; text-color: #0044AA; text-size: 11px;");
                        } else {
                            // Si no forma parte de la ruta corta, mantiene su color reglamentario por Neurotransmisor
                            String color = "#888888"; 
                            if (nt.equalsIgnoreCase("GLU") || nt.equalsIgnoreCase("ACH")) {
                                color = "blue";
                            } else if (nt.equalsIgnoreCase("DA")) {
                                color = "green";
                            } else if (nt.equalsIgnoreCase("GABA")) {
                                color = "red";
                            }
                            aristaVisual.setAttribute("ui.style", "fill-color: " + color + "; size: 1px;");
                        }
                    }
                    actual = actual.siguiente;
                }
            }
            
            // 5. Configurar el motor de renderizado oficial para GraphStream 2.0
            org.graphstream.ui.view.Viewer viewer = new org.graphstream.ui.swing_viewer.SwingViewer(graphVisual, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
            
            // 6. Obtener el panel de la vista integrada en Swing
            ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false); 
            
            // SOLUCIÓN AL GRÁFICO CORTADO: Ajustar dinámicamente al tamaño actual disponible de tu contenedor
            viewPanel.setPreferredSize(jScrollPane1.getSize());
            viewPanel.setSize(jScrollPane1.getSize()); 
            
            viewPanel.getCamera().setAutoFitView(false);
            
            // 7. Configuración del motor de fuerzas de distribución física
            graphVisual.setAttribute("layout.force", 0.15);       // Fuerza elástica calibrada para que no se expandan tanto
            graphVisual.setAttribute("layout.quality", 4);         // Máxima precisión de dibujado posicional
            
            // Activar el Layout automático continuo
            viewer.enableAutoLayout();
            
            // Hilo temporizado muy corto para forzar un encuadre centrado perfecto en pantalla
            new javax.swing.Timer(250, e -> {
                if (viewPanel.getCamera() != null) {
                    viewPanel.getCamera().resetView(); // Limpia zooms residuales erróneos
                    viewPanel.getCamera().setAutoFitView(true); // Fuerza el encuadre exacto al tamaño del JScrollPane
                }
            }).start();
            
            // Evitar cierres inesperados de hilos en cascada de Java Swing
            viewer.setCloseFramePolicy(org.graphstream.ui.view.Viewer.CloseFramePolicy.CLOSE_VIEWER);
            
            // 8. Ocultar las barras de scroll fijas del JScrollPane para que se vea más limpio el lienzo interactivo
            jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
            
            // 9. Incrustar el panel calibrado en tu ventana y refrescar la UI de Java
            jScrollPane1.setViewportView(viewPanel);
            jScrollPane1.revalidate();
            jScrollPane1.repaint();
            this.revalidate();
            this.repaint();
            
        } catch (Exception e) {
            System.err.println("Error crítico al renderizar el mapa visual: " + e.getMessage());
            e.printStackTrace(); 
        }
    }
    private boolean esAristaDeRutaOptima(String idOrigen, String idDestino) {
        if (ultimaRutaDijkstra == null || ultimaRutaDijkstra.length < 2) return false;
        for (int i = 0; i < ultimaRutaDijkstra.length - 1; i++) {
            if (ultimaRutaDijkstra[i].equals(idOrigen) && ultimaRutaDijkstra[i+1].equals(idDestino)) {
                return true;
            }
        }
        return false;
    }
// Añade esto al final de tu Interfazprincipal.java para corregir el error:
    private boolean esZonaAislada(String idNodo) {
        if (ultimasZonasAisladas == null) return false;
        for (String id : ultimasZonasAisladas) {
            if (id.equals(idNodo)) return true;
        }
        return false;
    }
    private void SimularlesioncerebralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularlesioncerebralActionPerformed
        // TODO add your handling code here:
        if (redNeuronal == null || redNeuronal.getCantidadNodos() == 0) {
            JOptionPane.showMessageDialog(this, "Debe cargar la red neuronal primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String idEliminar = JOptionPane.showInputDialog(this, "Ingrese el ID de la neurona a eliminar (Simular Lesión Focal):");
        if (idEliminar == null || idEliminar.trim().isEmpty()) return;
        idEliminar = idEliminar.trim().toUpperCase();

        // 1. Verificar si la neurona realmente existe antes de proceder
        if (redNeuronal.buscarNeurona(idEliminar) == null) {
            JOptionPane.showMessageDialog(this, "La neurona '" + idEliminar + "' no existe en la red.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Ejecutar la eliminación física en tu estructura de Grafo
        // (Esto remueve la neurona y todas las sinapsis que entraban o salían de ella)
        redNeuronal.eliminarNeurona(idEliminar);

        JOptionPane.showMessageDialog(this, 
                "¡Lesión Cerebral Simulada!\n\n" +
                "La neurona '" + idEliminar + "' y todas sus conexiones asociadas han sido destruidas.", 
                "Simulación de Lesión", JOptionPane.WARNING_MESSAGE);

        // ========================================================
        // 3. ¡SOLUCIÓN DE PERSISTENCIA! OFRECER GUARDAR CAMBIOS
        // ========================================================
        int respuesta = JOptionPane.showConfirmDialog(this, 
                "¿Desea guardar y exportar el estado actual de la red modificada (con la neurona eliminada) en el CSV?", 
                "Guardar Persistencia tras Lesión", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            guardarDatosEnArchivoCSV(); // Llama a la función que ya creamos con el JFileChooser
        }
        // ========================================================

        // 4. Refrescar el mapa visual de GraphStream para que la neurona desaparezca de la pantalla
        sincronizarGrafoVisual();
    }//GEN-LAST:event_SimularlesioncerebralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        // Corregido: Imprime el error en la consola de NetBeans sin usar 'logger'
        ex.printStackTrace(); 
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfazprincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFS;
    private javax.swing.JButton CalculoRutaOptima;
    private javax.swing.JButton CargarDiccionario;
    private javax.swing.JButton CargarRedNeuronal;
    private javax.swing.JButton DFS;
    private javax.swing.JButton ImplantarNuevaNeurona;
    private javax.swing.JButton SimularfatigaCognitiva;
    private javax.swing.JButton Simularlesioncerebral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
